# -*- mode: ruby -*-
# vi: set ft=ruby :

SERVER_MEMORY = "1024"
VMNAME = "lfcs_sandbox	"

PGPORT = "5433"
PGUSER = "postgres"
PGPASSWORD = "devved"
PGDATABASE = "pgrbackup_test"
PGVERSION = "10"
NODE_VER = "10.x"
DB_DIR="/home/vagrant/pgrbackup/vagrant/pgscripts/"

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
ETH0IP=$(ifconfig -a eth0 | grep "inet addr:")
echo "Networking: [$ETH0IP]"
SCRIPT

Vagrant.configure("2") do |config|

	config.vm.provider "virtualbox" do |vb, orvb|
		orvb.vm.synced_folder '../', '/home/vagrant/lfcs', create:true, :mount_options => ['dmode=775', 'fmode=777']
		orvb.vm.network "private_network", ip: "192.168.86.56"
		vb.memory = SERVER_MEMORY
		vb.customize ["modifyvm", :id, "--memory", SERVER_MEMORY]
	end

	config.vm.provider "hyperv" do |hv, orhv|
		orhv.vm.box = "generic/ubuntu1804"
		orhv.vm.synced_folder "../", "/home/vagrant/lfcs", create:true,
			type: "rsync", rsync__exclude: ".git/"
		orhv.vm.network "public_network"
		hv.memory = SERVER_MEMORY
		hv.maxmemory = SERVER_MEMORY
		hv.linked_clone = true
		hv.enable_virtualization_extensions = true
		hv.vmname = VMNAME
	end

	config.vm.define "lfcs_sandbox" do |testbox10|
		testbox10.vm.box = "bento/ubuntu-18.04"
		testbox10.vm.hostname = "testbox10.testing"
		testbox10.vm.provision "shell", inline: $script
		testbox10.vm.provision :shell do |s|
			s.path = "testbox.bootstrap.sh"
			s.env = {
				"PGPORT" => PGPORT,
				"PGUSER" => PGUSER,
				"PGPASSWORD" => PGPASSWORD,
				"PGDATABASE" => PGDATABASE,
				"PGVERSION" => PGVERSION,
				"NODE_VER" => NODE_VER,
				"DB_DIR" => DB_DIR
			}
		end
	end

end
